# Cloud Build configuration file
# This builds a Docker image, pushes it to Artifact Registry, and deploys to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/avestoai-466417/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/avestoai-466417/${_REPOSITORY}/${_SERVICE_NAME}:latest',
      '.'
    ]
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/avestoai-466417/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
    ]
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/avestoai-466417/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    ]
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/avestoai-466417/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '${_PORT}',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--service-account', '${_RUNTIME_SERVICE_ACCOUNT}',
      '--set-env-vars', 'ENV=${_ENVIRONMENT}'
    ]
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image']

# Options for the build
options:
  # Use Cloud Logging only (resolves the service account logging issue)
  logging: CLOUD_LOGGING_ONLY

  # Machine type for the build (adjust based on your needs)
  machineType: 'E2_HIGHCPU_8'

  # Disk size for the build
  diskSizeGb: 100

  # Substitution option
  substitutionOption: 'ALLOW_LOOSE'

# Specify the custom service account
serviceAccount: 'projects/avestoai-466417/serviceAccounts/my-ci-cd-sa@avestoai-466417.iam.gserviceaccount.com'

# Substitutions (variables) - these can be overridden when triggering the build
substitutions:
  # Artifact Registry repository name
  _REPOSITORY: 'my-docker-repo'

  # Service name for your Cloud Run service
  _SERVICE_NAME: 'my-app'

  # Region where to deploy Cloud Run service (should match Artifact Registry region)
  _REGION: 'us-central1'

  # Port your application listens on
  _PORT: '8080'

  # Memory allocation for Cloud Run service
  _MEMORY: '512Mi'

  # CPU allocation
  _CPU: '1'

  # Minimum instances (0 for scale-to-zero)
  _MIN_INSTANCES: '0'

  # Maximum instances
  _MAX_INSTANCES: '10'

  # Environment (dev, staging, prod)
  _ENVIRONMENT: 'dev'

  # Runtime service account for Cloud Run (can be same as build SA or different)
  _RUNTIME_SERVICE_ACCOUNT: 'my-ci-cd-sa@avestoai-466417.iam.gserviceaccount.com'

# Timeout for the entire build (default is 10 minutes)
timeout: '1200s'

# Tags for organizing builds
tags:
  - 'cloud-run'
  - 'docker'
  - 'artifact-registry'
  - '${_SERVICE_NAME}'
  - '${_ENVIRONMENT}'
